### PR TITLE
 CTCTRADERS-1528: Update the content for titles and labels for S&S pages

### PR DESCRIPTION
**Pull request by snehaprathipat1**

### CODE REVIEW

**Review by ashwinirudrappa — APPROVED** [review]

**Comment by snehaprathipat1** [comment]
test this please

**Comment by snehaprathipat1** [comment]
test this please

**Comment by snehaprathipat1** [comment]
test this please

**Comment by snehaprathipat1** [comment]
test this please

**Comment by snehaprathipat1** [comment]
test this please

**Pull request merged**
